"""Export every number the paper uses as a LaTeX macro. Single source of truth: results/processed/numbers.json,
written by the analysis code (never by hand). Output: paper/generated/numbers.tex.

numbers.json format: {"RAccOursQwen": {"value": 0.734, "fmt": "pct1", "source": "results/processed/main.csv#row=..."}}
Formats: pct0/pct1 (x100 + \\%), f2/f3 (fixed decimals), int, raw (string). Macro names MUST start with 'R'
(check_paper.py relies on that) and contain letters only.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FMT = {"pct0": lambda v: f"{100 * v:.0f}\\%", "pct1": lambda v: f"{100 * v:.1f}\\%", "f1": lambda v: f"{v:.1f}",
       "f2": lambda v: f"{v:.2f}", "f3": lambda v: f"{v:.3f}", "int": lambda v: f"{int(round(v)):,}".replace(",", "{,}"),
       "raw": str, "p3": lambda v: "{<}0.001" if v < 0.001 else f"{v:.3f}"}


def main() -> None:
    nums = json.loads((ROOT / "results" / "processed" / "numbers.json").read_text())
    out = ["% GENERATED by code/scripts/export_paper_numbers.py from results/processed/numbers.json. Do not edit."]
    for name, spec in sorted(nums.items()):
        assert re.fullmatch(r"R[A-Za-z]+", name), f"bad macro name {name}"
        out.append(f"\\newcommand{{\\{name}}}{{{FMT[spec.get('fmt', 'raw')](spec['value'])}\\xspace}}  % {spec.get('source', '')}")
        if spec.get("fmt") == "p3":  # relation-carrying twin for prose: $p\\<name>Rel$ -> "p < 0.001" / "p = 0.393"
            v = spec["value"]
            rel = "{<}\\,0.001" if v < 0.001 else f"{{=}}\\,{v:.3f}"
            out.append(f"\\newcommand{{\\{name}Rel}}{{{rel}\\xspace}}  % {spec.get('source', '')}")
    (ROOT / "paper" / "generated").mkdir(parents=True, exist_ok=True)
    (ROOT / "paper" / "generated" / "numbers.tex").write_text("\\RequirePackage{xspace}\n" + "\n".join(out) + "\n")
    print(len(nums), "macros")


if __name__ == "__main__":
    main()
