"""Generated LaTeX tables (numbers come straight from results/processed, never typed):
paper/generated/profile_table.tex (MCV profiles of both models with CIs) and paper/generated/compile_example.tex
(one compiled plan with its per-block values and certificate)."""
from __future__ import annotations

import json
import pickle
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "code"))
PROC, GEN = ROOT / "results/processed", ROOT / "paper/generated"
FAMS = [("facts", "Facts"), ("history", "History"), ("tool", "Tool")]
MODELS = ["qwen3:4b-instruct", "qwen3:8b"]


def name(part: str, key: str) -> str:
    k = key.replace("_", " ")
    if part == "interaction":
        return "$I$(" + k.replace("|", ", ") + ")"
    return ("short " if part == "short" else "") + k


def cell(r) -> str:
    if r is None:
        return "--"
    return f"{r.raw:+.2f} {{\\scriptsize[{r.lo:+.2f}, {r.hi:+.2f}]}}".replace("+0.00", "0.00").replace("-0.00", "0.00")


def profile_table() -> None:
    P = pd.read_csv(PROC / "profiles.csv")
    L = [r"\begin{tabular}{@{}llcc@{}}\toprule", r"Family & Term & Qwen3-4B & Qwen3-8B\\\midrule"]
    for fam, F in FAMS:
        d = P[P.family == fam]
        bases = [f"{d[d.model == m].base.iloc[0]:.2f}" if len(d[d.model == m]) else "--" for m in MODELS]
        L.append(f"{F} & base success & {bases[0]} & {bases[1]}\\\\")
        for part in ("mcv", "short", "interaction"):
            for key in sorted(d[d.part == part].key.unique()):
                cells = []
                for m in MODELS:
                    g = d[(d.model == m) & (d.part == part) & (d.key == key)]
                    cells.append(cell(g.iloc[0]) if len(g) else "--")
                L.append(f" & {name(part, key)} & {cells[0]} & {cells[1]}\\\\")
        L.append(r"\midrule" if fam != "tool" else r"\bottomrule")
    L.append(r"\end{tabular}")
    (GEN / "profile_table.tex").write_text("% GENERATED by code/scripts/make_tables.py. Do not edit.\n" + "\n".join(L) + "\n")


def compile_example(iid: str = "tool-0000", budget: int = 1000) -> None:
    from mcv.compile.policies import Embedder, mcv_values
    from mcv.data.build import load
    from mcv.ir.blocks import TokenCounter

    inst = next(x for x in load("test", "tool") if x.iid == iid)
    prof = json.loads((PROC / "profiles" / "qwen3-4b-instruct_tool.json").read_text())
    with (PROC / "profiles" / "qwen3-4b-instruct_tool.pkl").open("rb") as fh:
        vm = pickle.load(fh)
    counter = TokenCounter("qwen3:4b-instruct")
    vals = mcv_values(inst, counter, prof, vm, embedder=Embedder(ROOT / "results/cache/embeddings.sqlite"))
    ep = next(json.loads(l) for l in (ROOT / "results/raw/main_4b/episodes.jsonl").read_text().splitlines()
              if f'"{iid}"' in l and '"policy": "OURS"' in l and f'"budget": {budget},' in l)
    sel = ep["selection"]
    opt = [b for b in inst.blocks if b.id not in inst.mandatory_ids()]
    rows = sorted(opt, key=lambda b: -vals[b.id]["full"])
    shown = rows[:6] + [b for b in rows[6:] if b.id in sel][:2] + rows[-2:]
    seen, L = set(), []
    for b in shown:
        if b.id in seen:
            continue
        seen.add(b.id)
        label = b.id.replace("_", r"\_")
        if b.type.value == "tool_schema":
            label = r"\texttt{" + json.loads(b.variants["full"]).get("name", b.id).replace("_", r"\_") + "}" \
                if b.variants["full"].lstrip().startswith("{") else label
        L.append(f"{label} & {b.type.value.replace('_', ' ')} & {counter.block_cost(b)} & {vals[b.id]['full']:.3f} & "
                 f"{sel.get(b.id, '--')}\\\\")
    used = sum(counter.block_cost(inst.by_id()[k], v) for k, v in sel.items())
    c = ep["certificate"]
    out = [r"\begin{tabular}{@{}llrrl@{}}\toprule", r"Block & Type & Tokens & $\hat v$ & Chosen\\\midrule"] + L + [
        r"\midrule", f"\\multicolumn{{5}}{{@{{}}l}}{{{len(opt)} optional blocks; {len(sel) - len(inst.mandatory_ids())} "
        f"chosen; {used} of {budget} tokens; status {c['status']}, {1000 * c['seconds']:.1f} ms}}\\\\",
        r"\bottomrule\end{tabular}"]
    (GEN / "compile_example.tex").write_text("% GENERATED by code/scripts/make_tables.py. Do not edit.\n" + "\n".join(out) + "\n")


def main() -> None:
    GEN.mkdir(parents=True, exist_ok=True)
    profile_table()
    compile_example()
    print("tables written")


if __name__ == "__main__":
    main()
