"""Verbatim failure excerpts for the paper, pulled from the raw logs (never typed by hand) -> paper/generated/excerpts.tex."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "results/raw"


def tex(s: str, n: int = 160) -> str:
    s = " ".join(s.split())
    s = s if len(s) <= n else s[: n - 3].rstrip() + "..."
    for a, b in [("\\", r"\textbackslash{}"), ("{", r"\{"), ("}", r"\}"), ("_", r"\_"), ("%", r"\%"), ("&", r"\&"),
                 ("#", r"\#"), ("$", r"\$"), ("^", r"\^{}"), ("~", r"\~{}")]:
        s = s.replace(a, b) if a != "\\" else s.replace(a, "\x00")
    return s.replace("\x00", r"\textbackslash{}")


def main() -> None:
    inst = {}
    for line in (ROOT / "data/processed/instances.jsonl").read_text().splitlines():
        x = json.loads(line)
        inst[x["iid"]] = x
    ep = {}
    for run in ("main_4b", "main_4b_weak"):
        for line in (RAW / run / "episodes.jsonl").read_text().splitlines():
            r = json.loads(line)
            ep[(r["iid"], r["policy"], r["budget"])] = r

    def block(iid, bid):
        return next(b for b in inst[iid]["blocks"] if b["id"] == bid)["variants"]["full"]

    def goal(iid):
        return next(b for b in inst[iid]["blocks"] if b["type"] == "goal")["variants"]["full"].split("\n")[0]

    rows = []
    # (a) history at 1k: OURS drops the session holding the update; relevance keeps it
    iid = "history-0003"
    g = next(b["id"] for b in inst[iid]["blocks"] if b["meta"].get("gold"))
    upd = re.search(r'User: "[^"]*"', block(iid, g)).group(0)
    o, r2 = ep[(iid, "OURS", 1000)], ep[(iid, "B2", 1000)]
    rows.append(("History, 1k", f"{goal(iid)} Session holding the update: ``{upd}''. Kept by B2: "
                 f"{'yes' if g in r2['selection'] else 'no'}; by MCV: {'yes' if g in o['selection'] else 'no'}.",
                 f"MCV: {o['reply']}", f"B2: {r2['reply']}"))
    # (b) tool at 1k: LLMLingua-2 deletes the underscores of identifiers
    iid = "tool-0000"
    o, b3 = ep[(iid, "OURS", 1000)], ep[(iid, "B3", 1000)]
    rows.append(("Tool, 1k", goal(iid), f"MCV: {o['reply']}", f"B3: {b3['reply']}"))
    # (c) facts at 8k: all supporting paragraphs kept, distractors removed, answer type changes
    iid = "facts-0005"
    o, b0 = ep[(iid, "OURS", 8000)], ep[(iid, "B0", 1_000_000_000)]
    rows.append(("Facts, 8k", goal(iid), f"MCV: {o['reply']}", f"B0: {b0['reply']}"))
    out = [r"% GENERATED by code/scripts/make_excerpts.py from results/raw. Do not edit.",
           r"\begin{tabular}{@{}p{0.11\textwidth}p{0.45\textwidth}p{0.4\textwidth}@{}}\toprule",
           r"Case & Goal and context & Replies (verbatim)\\\midrule"]
    for case, ctx, a, b in rows:
        out.append(f"{case} & {tex(ctx, 330)} & \\texttt{{\\footnotesize {tex(a)}}}\\newline \\texttt{{\\footnotesize {tex(b)}}}\\\\")
    out.append(r"\bottomrule\end{tabular}")
    (ROOT / "paper/generated/excerpts.tex").write_text("\n".join(out) + "\n")
    print("wrote", len(rows), "excerpts")


if __name__ == "__main__":
    main()
