"""Verify every bib entry: DOI resolves at Crossref/DataCite AND doi.org, title (>=0.90 similarity) and first-author
surname match the registry, an abstract was read (refs/abstracts/<key>.txt), and \\cite keys <-> bib keys match exactly.
Also warns when an arXiv DOI is cited although the registry links a published version (prefer the published DOI).
Writes refs/VERIFY_REPORT.md. Exit code != 0 on ANY problem. Run before every paper build."""
from __future__ import annotations

import difflib
import json
import re
import sys
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
UA = {"User-Agent": "agentic-papers-refcheck/0.2 (research reproducibility; mailto:sangaraju1988@gmail.com)"}


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()
    s = re.sub(r"\\[a-z]+|[{}\\$]", "", s)
    return re.sub(r"[^a-z0-9]+", " ", s).strip()


def fetch(url: str):
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40) as r:
            return r.status, json.load(r)
    except urllib.error.HTTPError as e:
        return e.code, None
    except Exception:  # noqa: BLE001
        return 0, None


def resolves(doi: str):
    req = urllib.request.Request(f"https://doi.org/{doi}", headers=UA, method="HEAD")
    try:
        with urllib.request.urlopen(req, timeout=40) as r:
            return r.status < 400, r.geturl()
    except urllib.error.HTTPError as e:  # publisher landing pages often block HEAD/bots AFTER a valid redirect
        return (e.code in (403, 405, 429) and e.url != f"https://doi.org/{doi}"), f"{e.code} at {e.url}"
    except Exception as e:  # noqa: BLE001
        return False, str(e)[:80]


def parse_bib(text: str) -> list[dict]:
    out = []
    for m in re.finditer(r"@(\w+)\{([^,]+),(.*?)\n\}", text, re.S):
        f = {k.lower(): v for k, v in re.findall(r"(\w+)\s*=\s*\{(.*?)\},?\s*$", m.group(3), re.M)}
        out.append({"key": m.group(2).strip(), **f})
    return out


def main() -> int:
    bib = parse_bib((ROOT / "paper" / "references.bib").read_text())
    tex = "".join(p.read_text() for p in (ROOT / "paper").rglob("*.tex"))
    cited = {k.strip() for grp in re.findall(r"\\cite[a-z]*\{([^}]*)\}", tex) for k in grp.split(",") if k.strip()}
    rows, fails, warns = [], 0, []
    for e in bib:
        doi, key = e.get("doi", ""), e["key"]
        if not doi:
            rows.append((key, "-", "FAIL missing DOI", "", "", "", ""))
            fails += 1
            continue
        code, j = fetch(f"https://api.crossref.org/works/{urllib.parse.quote(doi)}")
        api = "crossref"
        if code != 200:
            code, j = fetch(f"https://api.datacite.org/dois/{urllib.parse.quote(doi)}")
            api = "datacite"
        sim, author_ok, redirect, status = 0.0, False, (False, ""), "FAIL"
        if code == 200 and j:
            if api == "crossref":
                t = j["message"]["title"][0]
                first = (j["message"].get("author") or [{}])[0].get("family", "")
            else:
                a = j["data"]["attributes"]
                t = a["titles"][0]["title"]
                c0 = a["creators"][0]
                first = c0.get("familyName") or c0["name"].split(",")[0]
                for rel in a.get("relatedIdentifiers", []):
                    if rel.get("relationType") == "IsVersionOf" and rel.get("relatedIdentifierType") == "DOI":
                        warns.append(f"{key}: arXiv DOI cited but a published version exists: {rel['relatedIdentifier']}")
            sim = difflib.SequenceMatcher(None, norm(t), norm(e.get("title", ""))).ratio()
            bib_first = norm(e.get("author", "").split(" and ")[0].split(",")[0])
            author_ok = norm(first) == bib_first
            redirect = resolves(doi)
            if sim >= 0.9 and author_ok and redirect[0]:
                status = "OK"
        abstract_ok = (ROOT / "refs" / "abstracts" / f"{key}.txt").exists()
        if not abstract_ok:
            status = "FAIL"
        fails += status != "OK"
        rows.append((key, doi, f"{status} ({api} {code})", f"{sim:.3f}", "yes" if author_ok else "NO",
                     "yes" if redirect[0] else f"NO {redirect[1]}", "yes" if abstract_ok else "NO"))
    keys = {e["key"] for e in bib}
    missing, uncited = sorted(cited - keys), sorted(keys - cited)
    fails += len(missing) + len(uncited)
    L = ["# Reference verification report", "", "Generated by `code/scripts/verify_refs.py`.", "",
         f"Entries: {len(bib)}; OK: {sum(r[2].startswith('OK') for r in rows)}; cited-but-missing: {len(missing)}; "
         f"never-cited: {len(uncited)}.", "",
         "| key | DOI | API | title sim | 1st author | doi.org | abstract read |", "|---|---|---|---|---|---|---|"]
    L += [f"| {' | '.join(r)} |" for r in rows]
    if missing:
        L += ["", "Cited but missing from bib: " + ", ".join(missing)]
    if uncited:
        L += ["", "In bib but never cited: " + ", ".join(uncited)]
    if warns:
        L += ["", "## Warnings (prefer published DOI)", ""] + [f"- {w}" for w in warns]
    L += ["", "RESULT: " + ("PASS" if fails == 0 else f"FAIL ({fails} problems)")]
    (ROOT / "refs" / "VERIFY_REPORT.md").write_text("\n".join(L) + "\n")
    print(L[-1])
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
